frr version 9.1
frr defaults datacenter
hostname client2
service integrated-vtysh-config
!
interface lo
 ip address 10.20.20.20/32
!
interface eth1
 ip address 10.20.20.0/31
!
router bgp 65160
 bgp router-id 10.20.20.20
 no bgp default ipv4-unicast
 neighbor 10.20.20.1 remote-as 65103
 address-family ipv4 unicast
  neighbor 10.20.20.1 activate
  network 10.20.20.20/32
 exit-address-family
!
ip route 0.0.0.0/0 10.20.20.1
!
line vty
