"""Generate Terraform configuration for a Cisco VXLAN EVPN fabric.

This script reads a JSON description of a fabric consisting of spines, leafs,
and border leaf pairs and writes a Terraform project that can be used to
generate base NX-OS configurations via the `local_file` provider.
"""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any, Dict, Iterable, List, Mapping

MODULES = {
    "nxos_switch/main.tf": """
terraform {
  required_providers {
    local = {
      source  = \"hashicorp/local\"
      version = \">= 2.4.0\"
    }
  }
}

variable \"hostname\" {
  description = \"Switch hostname\"
  type        = string
}

variable \"role\" {
  description = \"Logical role of the switch (spine, leaf, border)\"
  type        = string
}

variable \"management_ip\" {
  description = \"Management IP address\"
  type        = string
}

variable \"vpc_id\" {
  description = \"Optional VPC domain ID\"
  type        = number
  default     = null
}

resource \"local_file\" \"config\" {
  filename = \"${path.root}/generated/${var.hostname}.cfg\"
  content  = templatefile(\"${path.module}/templates/base.cfg\", {
    hostname      = var.hostname
    role          = var.role
    management_ip = var.management_ip
    vpc_id        = var.vpc_id
  })
}

output \"config_path\" {
  value = local_file.config.filename
}
""".strip()
,
    "nxos_switch/templates/base.cfg": """
! Autogenerated base configuration
hostname ${hostname}
!
vrf context management
  ip route 0.0.0.0/0 ${management_ip}
!
feature nv overlay
feature evpn
feature bgp
!
! Logical role: ${role}
%{ if vpc_id != null }
vpc domain ${vpc_id}
  role priority ${role == \"spine\" ? 10 : 20}
%{ endif }
""".strip()
,
    "nxos_border_pair/main.tf": """
terraform {
  required_providers {
    local = {
      source  = \"hashicorp/local\"
      version = \">= 2.4.0\"
    }
  }
}

variable \"vpc_id\" {
  description = \"VPC domain identifier\"
  type        = number
  default     = null
}

variable \"members\" {
  description = \"Border leaf members participating in the VPC pair\"
  type = list(object({
    hostname      = string
    management_ip = string
  }))
}

resource \"local_file\" \"config\" {
  for_each = { for member in var.members : member.hostname => member }

  filename = \"${path.root}/generated/${each.value.hostname}.cfg\"
  content  = templatefile(\"${path.module}/templates/border_member.cfg\", {
    hostname      = each.value.hostname
    management_ip = each.value.management_ip
    vpc_id        = var.vpc_id
  })
}

output \"config_paths\" {
  value = [for file in local_file.config : file.filename]
}
""".strip()
,
    "nxos_border_pair/templates/border_member.cfg": """
! Autogenerated border leaf configuration
hostname ${hostname}
!
interface mgmt0
  description Management interface
  ip address ${management_ip}/24
!
feature nv overlay
feature evpn
feature bgp
vpc domain ${vpc_id == null ? 0 : vpc_id}
  peer-keepalive destination ${management_ip}
""".strip()
}

TERRAFORM_HEADER = """
terraform {
  required_version = \">= 1.3.0\"

  required_providers {
    local = {
      source  = \"hashicorp/local\"
      version = \">= 2.4.0\"
    }

    null = {
      source  = \"hashicorp/null\"
      version = \">= 3.2.1\"
    }
  }
}
""".strip()

PREPARE_WORKSPACE = """
resource \"null_resource\" \"prepare_workspace\" {
  provisioner \"local-exec\" {
    command = \"mkdir -p ${path.root}/generated\"
  }
}
""".strip()


class FabricValidationError(ValueError):
    """Raised when the fabric description is invalid."""


def load_fabric(path: Path) -> Dict[str, Any]:
    with path.open("r", encoding="utf-8") as handle:
        try:
            data = json.load(handle)
        except json.JSONDecodeError as exc:
            raise FabricValidationError(f"Invalid JSON: {exc}") from exc
    return data


def validate_fabric(data: Mapping[str, Any]) -> Dict[str, Any]:
    fabric: Dict[str, Any] = {
        "fabric_name": data.get("fabric_name", "fabric"),
        "spines": _validate_switches(data.get("spines", []), "spine"),
        "leafs": _validate_switches(data.get("leafs", []), "leaf"),
        "border_leafs": _validate_border_pairs(data.get("border_leafs", [])),
    }

    if not fabric["spines"]:
        raise FabricValidationError("At least one spine must be defined.")
    if not fabric["leafs"]:
        raise FabricValidationError("At least one leaf must be defined.")

    return fabric


def _validate_switches(items: Any, role: str) -> List[Dict[str, Any]]:
    if not isinstance(items, list):
        raise FabricValidationError(f"{role.title()}s must be provided as a list.")

    validated: List[Dict[str, Any]] = []
    for index, entry in enumerate(items):
        if not isinstance(entry, Mapping):
            raise FabricValidationError(
                f"{role.title()} entry at index {index} must be an object."
            )
        name = entry.get("name")
        ip = entry.get("management_ip")
        if not name or not isinstance(name, str):
            raise FabricValidationError(
                f"{role.title()} entry at index {index} is missing a valid 'name'."
            )
        if not ip or not isinstance(ip, str):
            raise FabricValidationError(
                f"{role.title()} '{name}' is missing a valid 'management_ip'."
            )
        validated.append({"name": name, "management_ip": ip})
    return validated


def _validate_border_pairs(items: Any) -> List[Dict[str, Any]]:
    if not isinstance(items, list):
        raise FabricValidationError("Border leafs must be provided as a list.")

    validated: List[Dict[str, Any]] = []
    for index, entry in enumerate(items):
        if not isinstance(entry, Mapping):
            raise FabricValidationError(
                f"Border leaf pair at index {index} must be an object."
            )
        members = entry.get("members") or entry.get("leafs")
        if not isinstance(members, list) or not members:
            raise FabricValidationError(
                f"Border leaf pair at index {index} must include a non-empty 'members' list."
            )
        validated_members = _validate_switches(members, "border leaf member")
        pair_name = entry.get("pair_name") or entry.get("name") or f"pair_{index + 1}"
        vpc_id = entry.get("vpc_id")
        if vpc_id is not None and not isinstance(vpc_id, (int, float)):
            raise FabricValidationError(
                f"Border leaf pair '{pair_name}' has an invalid 'vpc_id'."
            )
        validated.append(
            {
                "pair_name": pair_name,
                "vpc_id": vpc_id,
                "members": validated_members,
            }
        )
    return validated


def sanitize(name: str) -> str:
    cleaned = re.sub(r"[^0-9A-Za-z_]+", "_", name)
    if cleaned and cleaned[0].isdigit():
        cleaned = f"_{cleaned}"
    return cleaned or "item"


def generate_main_tf(fabric: Mapping[str, Any]) -> str:
    blocks: List[str] = [TERRAFORM_HEADER, PREPARE_WORKSPACE]

    for index, spine in enumerate(fabric["spines"], start=1):
        module_name = f"spine_{index}_{sanitize(spine['name'])}"
        blocks.append(
            _render_switch_module(
                module_name,
                hostname=spine["name"],
                role="spine",
                management_ip=spine["management_ip"],
                vpc_id="null",
            )
        )

    for index, leaf in enumerate(fabric["leafs"], start=1):
        module_name = f"leaf_{index}_{sanitize(leaf['name'])}"
        blocks.append(
            _render_switch_module(
                module_name,
                hostname=leaf["name"],
                role="leaf",
                management_ip=leaf["management_ip"],
                vpc_id="null",
            )
        )

    for index, pair in enumerate(fabric["border_leafs"], start=1):
        module_name = f"border_pair_{index}_{sanitize(pair['pair_name'])}"
        blocks.append(_render_border_pair_module(module_name, pair))

    return "\n\n".join(blocks) + "\n"


def _render_switch_module(
    module_name: str,
    *,
    hostname: str,
    role: str,
    management_ip: str,
    vpc_id: str,
) -> str:
    return (
        f"module \"{module_name}\" {{\n"
        f"  source = \"./modules/nxos_switch\"\n"
        f"  depends_on = [null_resource.prepare_workspace]\n\n"
        f"  hostname      = \"{hostname}\"\n"
        f"  role          = \"{role}\"\n"
        f"  management_ip = \"{management_ip}\"\n"
        f"  vpc_id        = {vpc_id}\n"
        f"}}"
    )


def _render_border_pair_module(module_name: str, pair: Mapping[str, Any]) -> str:
    members_hcl = "\n".join(
        f"    {{\n      hostname      = \"{member['name']}\"\n      management_ip = \"{member['management_ip']}\"\n    }}"
        for member in pair["members"]
    )
    vpc_id = "null" if pair["vpc_id"] is None else str(int(pair["vpc_id"]))

    return (
        f"module \"{module_name}\" {{\n"
        f"  source = \"./modules/nxos_border_pair\"\n"
        f"  depends_on = [null_resource.prepare_workspace]\n\n"
        f"  vpc_id = {vpc_id}\n"
        f"  members = [\n{members_hcl}\n  ]\n"
        f"}}"
    )


def write_modules(output_dir: Path) -> None:
    for relative_path, content in MODULES.items():
        destination = output_dir / "modules" / relative_path
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(content + "\n", encoding="utf-8")


def write_main_tf(output_dir: Path, fabric: Mapping[str, Any]) -> Path:
    content = generate_main_tf(fabric)
    destination = output_dir / "main.tf"
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(content, encoding="utf-8")
    return destination


def generate(fabric_path: Path, output_dir: Path) -> None:
    data = load_fabric(fabric_path)
    fabric = validate_fabric(data)
    write_modules(output_dir)
    main_tf_path = write_main_tf(output_dir, fabric)
    print(f"Terraform configuration written to {main_tf_path}")


def build_argument_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Generate Terraform code for a Cisco VXLAN EVPN fabric based on a JSON description."
        )
    )
    parser.add_argument(
        "fabric",
        type=Path,
        help="Path to the JSON file describing the fabric.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("generated_terraform"),
        help="Directory where the Terraform project will be created.",
    )
    return parser


def main(argv: Iterable[str] | None = None) -> None:
    parser = build_argument_parser()
    args = parser.parse_args(argv)
    generate(args.fabric, args.output)


if __name__ == "__main__":
    main()
