frr version 9.1
frr defaults datacenter
hostname fw1
service integrated-vtysh-config
!
vrf blue
 vni 10001
!
vrf red
 vni 10002
!
interface eth1
 vrf blue
 ip address 172.16.10.1/31
!
interface eth2
 vrf red
 ip address 172.16.20.1/31
!
interface eth3
 ip address 172.31.0.5/31
!
router bgp 65200
 bgp router-id 172.31.0.5
 no bgp default ipv4-unicast
 neighbor 172.31.0.4 remote-as 65101
 address-family ipv4 unicast
  neighbor 172.31.0.4 activate
  network 172.31.0.5/31
 exit-address-family
!
router bgp 65200 vrf blue
 no bgp default ipv4-unicast
 neighbor 172.16.10.0 remote-as 65101
 address-family ipv4 unicast
  neighbor 172.16.10.0 activate
  neighbor 172.16.10.0 default-originate
  network 172.16.10.0/31
 exit-address-family
!
router bgp 65200 vrf red
 no bgp default ipv4-unicast
 neighbor 172.16.20.0 remote-as 65101
 address-family ipv4 unicast
  neighbor 172.16.20.0 activate
  neighbor 172.16.20.0 default-originate
  network 172.16.20.0/31
 exit-address-family
!
ip route 0.0.0.0/0 172.31.0.4
!
line vty
