frr version 9.1
frr defaults datacenter
hostname edge1
service integrated-vtysh-config
!
interface lo
 ip address 8.8.8.8/32
!
interface eth1
 ip address 172.31.0.0/31
!
router bgp 65300
 bgp router-id 8.8.8.8
 no bgp default ipv4-unicast
 neighbor 172.31.0.1 remote-as 65101
 address-family ipv4 unicast
  neighbor 172.31.0.1 activate
  network 8.8.8.8/32
 exit-address-family
!
line vty
